//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokeripeli.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pokeripeli.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse haluamasi panos ja paina Pelaa!.
        /// </summary>
        public static string avustusAlkutilanne {
            get {
                return ResourceManager.GetString("avustusAlkutilanne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahat loppu. Aloita uusi peli!.
        /// </summary>
        public static string avustusRahatLoppu {
            get {
                return ResourceManager.GetString("avustusRahatLoppu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arvaa onko kortti pieni (A-6).
        /// </summary>
        public static string avustusTuplaus1 {
            get {
                return ResourceManager.GetString("avustusTuplaus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vai iso (8-K).
        /// </summary>
        public static string avustusTuplaus2 {
            get {
                return ResourceManager.GetString("avustusTuplaus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aloita uusi peli Tiedosto-valikosta!.
        /// </summary>
        public static string avustusUusipeli {
            get {
                return ResourceManager.GetString("avustusUusipeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse haluamasi kortit klikkaamalla.
        /// </summary>
        public static string avustusValitsekortit1 {
            get {
                return ResourceManager.GetString("avustusValitsekortit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja paina Pelaa!.
        /// </summary>
        public static string avustusValitsekortit2 {
            get {
                return ResourceManager.GetString("avustusValitsekortit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valitse Voitot talteen tai Tuplaa!.
        /// </summary>
        public static string avustusVoittotilanne {
            get {
                return ResourceManager.GetString("avustusVoittotilanne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei voittoa!.
        /// </summary>
        public static string ilmoitusEivoittoa {
            get {
                return ResourceManager.GetString("ilmoitusEivoittoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahat loppu. Game Over!.
        /// </summary>
        public static string ilmoitusRahatloppu {
            get {
                return ResourceManager.GetString("ilmoitusRahatloppu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuplaus: .
        /// </summary>
        public static string ilmoitusTuplaus {
            get {
                return ResourceManager.GetString("ilmoitusTuplaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to . Voitit  .
        /// </summary>
        public static string ilmoitusTuplausEijatku {
            get {
                return ResourceManager.GetString("ilmoitusTuplausEijatku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Väärä arvaus, menetit voittosi!.
        /// </summary>
        public static string ilmoitusVaaraArvaus {
            get {
                return ResourceManager.GetString("ilmoitusVaaraArvaus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oikein. Voitit .
        /// </summary>
        public static string ilmoitusVoitto {
            get {
                return ResourceManager.GetString("ilmoitusVoitto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lukittu.
        /// </summary>
        public static string korttiLukittuTeksti {
            get {
                return ResourceManager.GetString("korttiLukittuTeksti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Iso.
        /// </summary>
        public static string labelIso {
            get {
                return ResourceManager.GetString("labelIso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rahaa.
        /// </summary>
        public static string labelOmatRahat {
            get {
                return ResourceManager.GetString("labelOmatRahat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pelaa.
        /// </summary>
        public static string labelPelaa {
            get {
                return ResourceManager.GetString("labelPelaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Pieni.
        /// </summary>
        public static string labelPieni {
            get {
                return ResourceManager.GetString("labelPieni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tuplaa.
        /// </summary>
        public static string labelTuplaa {
            get {
                return ResourceManager.GetString("labelTuplaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Voitot talteen.
        /// </summary>
        public static string labelVoitot {
            get {
                return ResourceManager.GetString("labelVoitot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voitot.
        /// </summary>
        public static string labelVoitotYhteensa {
            get {
                return ResourceManager.GetString("labelVoitotYhteensa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avustus.
        /// </summary>
        public static string menuAvustus {
            get {
                return ResourceManager.GetString("menuAvustus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lopeta.
        /// </summary>
        public static string menuLopeta {
            get {
                return ResourceManager.GetString("menuLopeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Näytä.
        /// </summary>
        public static string menuNayta {
            get {
                return ResourceManager.GetString("menuNayta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ennätykset.
        /// </summary>
        public static string menuNaytaennatykset {
            get {
                return ResourceManager.GetString("menuNaytaennatykset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohje.
        /// </summary>
        public static string menuOhje {
            get {
                return ResourceManager.GetString("menuOhje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tallenna ennätys.
        /// </summary>
        public static string menuTallenna {
            get {
                return ResourceManager.GetString("menuTallenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiedosto.
        /// </summary>
        public static string menuTiedosto {
            get {
                return ResourceManager.GetString("menuTiedosto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tietoja.
        /// </summary>
        public static string menuTietoja {
            get {
                return ResourceManager.GetString("menuTietoja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyhjennä ennätykset.
        /// </summary>
        public static string menuTyhjenna {
            get {
                return ResourceManager.GetString("menuTyhjenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Työkalut.
        /// </summary>
        public static string menuTyokalut {
            get {
                return ResourceManager.GetString("menuTyokalut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uusi peli.
        /// </summary>
        public static string menuUusipeli {
            get {
                return ResourceManager.GetString("menuUusipeli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaihda kieli.
        /// </summary>
        public static string menuVaihdakieli {
            get {
                return ResourceManager.GetString("menuVaihdakieli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei tarpeeksi voittoja uuteen ennätykseen!.
        /// </summary>
        public static string messageEiEnnatysta {
            get {
                return ResourceManager.GetString("messageEiEnnatysta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ei ennätystä tallennettavaksi.
        /// </summary>
        public static string messageEiEnnatystaOtsikko {
            get {
                return ResourceManager.GetString("messageEiEnnatystaOtsikko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko poistaa kaikki ennätykset?.
        /// </summary>
        public static string messageEnnatyspoisto {
            get {
                return ResourceManager.GetString("messageEnnatyspoisto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ennätysten poistaminen.
        /// </summary>
        public static string messageEnnatyspoistoOtsikko {
            get {
                return ResourceManager.GetString("messageEnnatyspoistoOtsikko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko lopettaa ja sulkea pelin?.
        /// </summary>
        public static string messageLopetus {
            get {
                return ResourceManager.GetString("messageLopetus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pelin sulkeminen.
        /// </summary>
        public static string messageLopetusOtsikko {
            get {
                return ResourceManager.GetString("messageLopetusOtsikko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haluatko vaihtaa kielen englanniksi? Kieli vaihtuu kun käynnistät ohjelman uudelleen..
        /// </summary>
        public static string messageVaihdakieli {
            get {
                return ResourceManager.GetString("messageVaihdakieli", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kielen vaihto.
        /// </summary>
        public static string messageVaihdakieliOtsikko {
            get {
                return ResourceManager.GetString("messageVaihdakieliOtsikko", resourceCulture);
            }
        }
    }
}
