//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallennaDialog.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TallennaDialog.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Peruuta.
        /// </summary>
        public static string buttonPeruuta {
            get {
                return ResourceManager.GetString("buttonPeruuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tallenna.
        /// </summary>
        public static string buttonTallenna {
            get {
                return ResourceManager.GetString("buttonTallenna", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alkuraha:.
        /// </summary>
        public static string labelAlkuraha {
            get {
                return ResourceManager.GetString("labelAlkuraha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nimimerkki:.
        /// </summary>
        public static string labelNimimerkki {
            get {
                return ResourceManager.GetString("labelNimimerkki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ennätyksen tallennus.
        /// </summary>
        public static string labelOtsikko {
            get {
                return ResourceManager.GetString("labelOtsikko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syötä nimimerkki!.
        /// </summary>
        public static string labelVirheTyhja {
            get {
                return ResourceManager.GetString("labelVirheTyhja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virheellinen merkki. Vain aakkoset kelpaavat!.
        /// </summary>
        public static string labelVirheVaarin {
            get {
                return ResourceManager.GetString("labelVirheVaarin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voitot:.
        /// </summary>
        public static string labelVoitot {
            get {
                return ResourceManager.GetString("labelVoitot", resourceCulture);
            }
        }
    }
}
