//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoittoTaulukko.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VoittoTaulukko.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaksiparia.
        /// </summary>
        public static string labelKaksiparia {
            get {
                return ResourceManager.GetString("labelKaksiparia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolmoset.
        /// </summary>
        public static string labelKolmoset {
            get {
                return ResourceManager.GetString("labelKolmoset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neloset.
        /// </summary>
        public static string labelNeloset {
            get {
                return ResourceManager.GetString("labelNeloset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suora.
        /// </summary>
        public static string labelSuora {
            get {
                return ResourceManager.GetString("labelSuora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Täyskäsi.
        /// </summary>
        public static string labelTayskasi {
            get {
                return ResourceManager.GetString("labelTayskasi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Väri.
        /// </summary>
        public static string labelVari {
            get {
                return ResourceManager.GetString("labelVari", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Värisuora.
        /// </summary>
        public static string labelVarisuora {
            get {
                return ResourceManager.GetString("labelVarisuora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viitoset.
        /// </summary>
        public static string labelViitoset {
            get {
                return ResourceManager.GetString("labelViitoset", resourceCulture);
            }
        }
    }
}
